# Change these first
owner: OpenEastleigh # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Open Eastleigh
    url: https://www.openeastleigh.uk
  - name: The Eastleigh Manifesto
    url: https://manifesto.openeastleigh.uk
  - name: Eastleigh Handbook
    url: https://handbook.openeastleigh.uk

workflowSchedule:
  uptime: "0 */3 * * *"

user-agent: eom-bot

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.openeastleigh.uk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://www.openeastleigh.uk/images/logo.png
  name: Open Eastleigh Status
  introTitle: "Latest status of Open Eastleigh tools."
  introMessage: "**Note:** the Groupthink tool, which manages The Eastleigh Manifesto, sleeps after 30 mins of inactivity and can be slow to respond."
  navbar:
    - title: Open Eastleigh
      href: https://www.openeastleigh.uk/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
